require:
  - rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - spec/**/*.rb
    - vendor/bundle/**/*

Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 8
