Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/ParallelAssignment:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - spec/**/*.rb

Metrics/ClassLength:
  Max: 200

Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 8

Style/RescueStandardError:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false