require:
  - rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/ParallelAssignment:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - spec/**/*.rb
    - vendor/bundle/**/*

Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false